# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'On24ScreenShare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for On24ScreenShare

end

target 'OpenTok Live' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenTok Live

end
